package product

type ApiGroup struct {
	// Code generated by github.com/yunxiaoyang01/go-mall/mall-admin Begin; DO NOT EDIT.

	PmsProductApi
	// Code generated by github.com/yunxiaoyang01/go-mall/mall-admin End; DO NOT EDIT.
}
