package {{ .PackageName }}


type ServiceGroup struct {
    // Code generated by github.com/yunxiaoyang01/go-mall/server Begin; DO NOT EDIT.

	// Code generated by github.com/yunxiaoyang01/go-mall/server End; DO NOT EDIT.
}

