package {{ .PackageName }}


type ServiceGroup struct {
    // Code generated by github.com/yunxiaoyang01/go-mall/mall-admin Begin; DO NOT EDIT.

	// Code generated by github.com/yunxiaoyang01/go-mall/mall-admin End; DO NOT EDIT.
}

