package {{ .PackageName }}

type ApiGroup struct {
	// Code generated by github.com/yunxiaoyang01/go-mall/go-mall-admin Begin; DO NOT EDIT.

	// Code generated by github.com/yunxiaoyang01/go-mall/go-mall-admin End; DO NOT EDIT.
}
