package product

type RouterGroup struct {
    // Code generated by github.com/yunxiaoyang01/go-mall/mall-admin Begin; DO NOT EDIT.

	PmsProductRouter
	// Code generated by github.com/yunxiaoyang01/go-mall/mall-admin End; DO NOT EDIT.
}
